import rtconfig
Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

CPPPATH = [cwd, str(Dir('#'))]
group = DefineGroup('sample_mjpeg', src, depend = ['RT_USING_SAMPLE_MJPEG'], CPPPATH = CPPPATH)

Return('group')

