import rtconfig
Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

CPPPATH = [cwd, str(Dir('#'))]
group = DefineGroup('sample_overlay', src, depend = ['RT_USING_SAMPLE_OVERLAY'], CPPPATH = CPPPATH)

Return('group')

