import rtconfig
Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

CPPPATH = [cwd, cwd + '/..',cwd + '/../inc']
group = DefineGroup('libvlcview', src, depend = ['RT_USING_LIBVLC'], CPPPATH = CPPPATH)

Return('group')

